name: Trigger auto deployment for containerapp test-cli

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-cli-AutoDeployTrigger-7dc91255-af48-4fb3-aea9-89a06e552172.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: catestcli391264899acr.azurecr.io
          username: ${{ secrets.TESTCLI_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTCLI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: catestcli391264899acr.azurecr.io/mcr.microsoft.com/azuredocs/containerapps-helloworld:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTCLI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n test-cli -g d-testcli --server catestcli391264899acr.azurecr.io --username  ${{ secrets.TESTCLI_REGISTRY_USERNAME }} --password ${{ secrets.TESTCLI_REGISTRY_PASSWORD }}
            az containerapp update -n test-cli -g d-testcli --image catestcli391264899acr.azurecr.io/mcr.microsoft.com/azuredocs/containerapps-helloworld:${{ github.sha }}
